:- module(facts,[]).

movie(casper).
movie(cinderella).
movie(wonderpark).
movie(snow_white).
movie(pee_mak).
movie(jandara2).
movie(unfaithful).
movie(fifty_shade_of_grey).
movie(the_lego).
movie(lalita).
movie(up).
movie(cafe_funiculi).
movie(captain_marvel).
movie(sangkrasue).
movie(blind).
movie(city_hunter).
movie(the_kid_who_would_be_king).
movie(mar_queen_of_scots).
movie(dumbo).
movie(masked_rider).
movie(us).
movie(shazam).
movie(hellboy).
movie(pet_sematary).
movie(the_queens_corgi).
movie(avenger_endgame).
movie(five_feet_apart).
movie(pokemon_detective_pikachu).
movie(john_wick3).
movie(aladdin).
movie(brightburn).
movie(godzilla_king_of_the_master).
movie(godzilla).
movie(x-men_dark_phoenix).
movie(secret_life_of_pet2).
movie(men_in_black_international).
movie(toy_story4).
movie(charlies_angel).
movie(spider-man_far_from_home).
movie(annabelle3).
movie(the_lion_king).
movie(fast_and_furious_hobbs_and_shaw).
movie(the_new_mutants).
movie(artemis_fowl).
movie(open_upon_a_time_in_hollywood).
movie(it2).
movie(abominable).
movie(joker).
movie(doraemon_nobita_chronicle_of_the_monn_exploration).
movie(sonic).
movie(frozen2).
movie(wonder_women_1984).
movie(star_war9).
movie(how_to_train_your_dragon).
movie(escape_room).
movie(glass).
movie(the_legend_of_muaythai_9stara).
is_type(alita,action).
is_type(cafe_funiculi,adventure).
is_type(the_lego,action).
is_type(the_lego,adventure).
is_type(the_lego,animation).
is_type(captain_marvel,action).
is_type(captain_marvel,adventure).
is_type(captain_marvel,sci-fi).
is_type(sangkrasue,drama).
is_type(blind,drama).
is_type(city_hunter,action).
is_type(city_hunter,comedy).
is_type(city_hunter,crime).
is_type(the_kid_who_would_be_king,adventure).
is_type(the_kid_who_would_be_king,fantasy).
is_type(mary_queen_of_scots,drama).
is_type(dumbo,animation).
is_type(dumbo,fatasy).
is_type(masked_rider,action).
is_type(us,horror).
is_type(us,thriller).
is_type(shazam,action).
is_type(hellboy,action).
is_type(hellboy,adventure).
is_type(hellboy,action).
is_type(hellboy,adventure).
is_type(hellboy,fantasy).
is_type(pet_sematary,horror).
is_type(the_queens_corgi,animation).
is_type(aventure_end_game,action).
is_type(five_feet_apart,romantic).
is_type(pokemon_detective_pikachu,animation).
is_type(pokemon_detective_pikachu,fantasy).
is_type(john_wick3,action).
is_type(john_wick3,crime).
is_type(john_wick3,thriller).
is_type(aladdin,adventure).
is_type(aladdin,fantasy).
is_type(brightburn,horror).
is_type(godzilla,action).
is_type(godzilla,adventure).
is_type(godzilla,fantasy).
is_type(x-men_dark_phoenix,action).
is_type(x-men_dark_phoenix,adventure).
is_type(x-men_dark_phoenix,sci-fi).
is_type(secret_life_of_pet2,adventure).
is_type(secret_life_of_pet2,animation).
is_type(secret_life_of_pet2,comedy).
is_type(men_in_black_international,action).
is_type(men_in_black_international,comedy).
is_type(men_in_black_international,sci-fi).
is_type(toy_story4,adventure).
is_type(toy_story4,animation).
is_type(toy_story4,comedy).
is_type(charlies_angel,crime).
is_type(charlies_angel,drama).
is_type(spider-man_far_from_home,action).
is_type(spider-man_far_from_home,adventure).
is_type(spider-man_far_from_home,comedy).
is_type(annabelle3,horror).
is_type(the_lion_king,adventure).
is_type(the_lion_king,animation).
is_type(fast_and_furious_hobbs_and_shaw,action).
is_type(the_new_mutants,action).
is_type(the_new_mutants,horror).
is_type(the_new_mutants,sci-fi).
is_type(artemis_fowl,action).
is_type(artemis_fowl,adventure).
is_type(open_upon_a_time_in_hollywood,comedy).
is_type(it2,horror).
is_type(it2,thriller).
is_type(abominable,adventure).
is_type(abominable,animation).
is_type(abominable,comedy).
is_type(joker,crime).
is_type(joker,thriller).
is_type(doraemon_nobita_chronicle_of_the_monn_exploration,animation).
is_type(doraemon_nobita_chronicle_of_the_monn_exploration,adventure).
is_type(sonic,action).
is_type(sonic,animation).
is_type(frozen2,animation).
is_type(frozen2,fantasy).
is_type(wonder_women_1984,action).
is_type(star_war9,action).
is_type(star_war9,adventure).
is_type(star_war9,fantasy).
is_type(how_to_train_your_dragon,animation).
is_type(how_to_train_your_dragon,adventure).
is_type(escape_room,thriller).
is_type(glass,sci-fi).
is_type(glass,action).
is_type(the_legend_of_muaythai_9stara,animation).
is_type(the_legend_of_muaythai_9stara,fantasy).
movie_age_range_start(up,0).
movie_age_range_start(the_kid_who_would_be_king,0).
movie_age_range_start(dumbo,0).
movie_age_range_start(wonderpark,0).
movie_age_range_start(how_to_train_your_dragon,0).
movie_age_range_start(casper,0).
movie_age_range_start(cinderella,0).
movie_age_range_start(snow_white,0).
movie_age_range_start(sangkrasue,13).
movie_age_range_start(captain_marvel,13).
movie_age_range_start(city_hunter,13).
movie_age_range_start(five_feet_apart,13).
movie_age_range_start(pee_mak,13).
movie_age_range_start(jan_dara2,18).
movie_age_range_start(john_wick3,18).
movie_age_range_start(unfaithful,18).
movie_age_range_start(us,18).
movie_age_range_start(fifty_shade_of_grey,18).
movie_age_range_end(up,200).
movie_age_range_end(the_kid_who_would_be_king,200).
movie_age_range_end(dumbo,200).
movie_age_range_end(wonderpark,200).
movie_age_range_end(how_to_train_your_dragon,200).
movie_age_range_end(casper,200).
movie_age_range_end(cinderella,200).
movie_age_range_end(snow_white,200).
movie_age_range_end(sangkrasue,200).
movie_age_range_end(captain_marvel,200).
movie_age_range_end(city_hunter,200).
movie_age_range_end(five_feet_apart,200).
movie_age_range_end(pee_mak,200).
movie_age_range_end(jan_dara2,200).
movie_age_range_end(john_wick3,200).
movie_age_range_end(unfaithful,200).
movie_age_range_end(us,200).
movie_age_range_end(fifty_shade_of_grey,200).
feeling(sad).
feeling(happy).
feeling(stress).
feeling(in_love).
feeling(boring).
feeling_to_watch(jandara2,sad).
feeling_to_watch(up,sad).
feeling_to_watch(sangkrasue,sad).
feeling_to_watch(john_wick3,happy).
feeling_to_watch(captain_marvel,happy).
feeling_to_watch(city_hunter,happy).
feeling_to_watch(the_kid_who_would_be_king,happy).
feeling_to_watch(dumbo,happy).
feeling_to_watch(wonderpark,happy).
feeling_to_watch(unfaithful,stress).
feeling_to_watch(five_feet_apart,stress).
feeling_to_watch(how_to_train_your_dragon,stress).
feeling_to_watch(fifty_shade_of_gray,in_love).
feeling_to_watch(five_feet_apart,in_love).
feeling_to_watch(cinderella,in_love).
feeling_to_watch(snow_white,in_love).
feeling_to_watch(us,boring).
feeling_to_watch(pee_mak,boring).
feeling_to_watch(casper,boring).
state(public_state).
state(private_state).
state_to_watch_movie(up,private_state).
state_to_watch_movie(the_kid_who_would_be_king,private_state).
state_to_watch_movie(dumbo,private_state).
state_to_watch_movie(wonderpark,private_state).
state_to_watch_movie(how_to_train_your_dragon,private_state).
state_to_watch_movie(casper,private_state).
state_to_watch_movie(cinderella,private_state).
state_to_watch_movie(snow_white,private_state).
state_to_watch_movie(sangkrasue,private_state).
state_to_watch_movie(captain_marvel,private_state).
state_to_watch_movie(city_hunter,private_state).
state_to_watch_movie(five_feet_apart,private_state).
state_to_watch_movie(pee_mak,private_state).
state_to_watch_movie(jandara2,private_state).
state_to_watch_movie(john_wick3,private_state).
state_to_watch_movie(unfaithful,private_state).
state_to_watch_movie(us,private_state).
state_to_watch_movie(fifty_shade_of_grey,private_state).
state_to_watch_movie(up,public_state).
state_to_watch_movie(the_kid_who_would_be_king,public_state).
state_to_watch_movie(dumbo,public_state).
state_to_watch_movie(wonderpark,public_state).
state_to_watch_movie(how_to_train_your_dragon,public_state).
state_to_watch_movie(casper,public_state).
state_to_watch_movie(cinderella,public_state).
state_to_watch_movie(snow_white,public_state).
state_to_watch_movie(sangkrasue,public_state).
state_to_watch_movie(captain_marvel,public_state).
state_to_watch_movie(city_hunter,public_state).
state_to_watch_movie(five_feet_apart,public_state).
state_to_watch_movie(pee_mak,public_state).
